version: "3.8"
services:
  molory-api:
    container_name: molory-api-prod
    build: 
      context: .
      args: 
        NODE_ENV: production
        PORT: 8087
    ports:
      - "8087:8087"
    volumes:
      - ./:/app
      # - /app/node_modules
    env_file:
      - ./.env
    # environment:
    #   - NODE_ENV=development
    command: sh -c "npx prisma db push && npm run dev"
networks:
  default:
    name: utils_default
    external: true
