version: "3.8"
services:
  node-app-dev:
    build: 
      context: .
      args: 
        NODE_ENV: development
        PORT: 8086
    ports:
      - "8086:8086"
    volumes:
      - ./:/app
      # - /app/node_modules
    env_file:
      - ./.env.dev
    # environment:
    #   - NODE_ENV=development
    command: npm run dev
