version: "3.8"
services:
  molory-api:
    container_name: molory-api
    build: 
      context: .
      args: 
        NODE_ENV: production
        PORT: 8086
    ports:
      - "8086:8086"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.dev
    # environment:
    #   - NODE_ENV=development
    command: sh -c "npx prisma db push && npm run dev"
networks:
  default:
    name: utils_default
    external: true
