@hostname = http://0.0.0.0
@port = 8086
@host = {{hostname}}:{{port}}
@contentTypeJson = application/json
###

# Login with phone number
# @prompt phoneNumber
# @name login
POST {{host}}/api/auth/send-otp HTTP/1.1
content-type: application/json

{
    "phoneNumber": "{{phoneNumber}}",
    "action": "signin"
}
###

@authTmpToken = {{login.response.body.token}}



# Confirm OTP
# @prompt otp
# @name confirmOtp
POST {{host}}/api/auth/verify-otp HTTP/1.1
Authorization: Bearer {{authTmpToken}}
content-type: application/json

{
    "otp": "{{otp}}",
    "device": {
        "id": "502A26A3-497E-41B9-9F64-E728AAFFF547",
        "platform": "web",
        "token": "c_bmxTMHs0iQtrXcznWirlAPA91bHto8JLS3zGixD0kvXYyklZDVC1wssC9fRPFmJY1j0q7dgtu7FKLbdQRMJxC5kAImXqW-Eu7Nv4OUVhKYKuOF73mzCP7cj_v5srckOojnpCU5ve4FFpRCj3w0iNQj0i66_6mxB7"
    }
}
### 


@authToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjU3ODQ4NDk2fQ.d9iic9WSRQFoGoIV6oZlPBURGyud9ZoyfyyN6GMTuok



#    Search for a route
# @prompt date
# @prompt departure
# @prompt arrival
# @name searchRoute
GET {{host}}/api/route?date={{date}}&departure={{departure}}&arrival={{arrival}} HTTP/1.1
Authorization: Bearer {{authToken}}
###


#    Get a Route infos
#    @prompt routeId
#    @name getRouteInfo
GET {{host}}/api/route/{{routeId}} HTTP/1.1
Authorization: Bearer {{authToken}}
###
