name: Docker Image CI

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: npm install

    - name: build dist folder
      run: tsc -p tsconfig.release.json
      
    - name: Push to dockerhub
      uses: docker/build-push-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPOSITORY}}
        file: ./docker-compose.prod.yml
        tags: latest, ${{github.run_number}}
      
